title: Flurin Gishamer
url: "https://gishamer.io"
baseurl: ""
repository: gishamer/gishamer.github.io

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/gishamer"
footer_text: "Wanna try?"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Blog"
   link: "https://fluringishamer.substack.com/"
 - name: "Github"
   link: "https://github.com/gishamer"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/fluringishamer/"
